export enum ERROR_CODE {
	MISSING_ARGUMENTS,
	INVALID_ARGUMENT_VALUE,
	UNKNOWN_COMMAND,
	PATH_NOT_FOUND,
	NOT_A_FILE,
	NOT_A_DIRECTORY,
	INVALID_JSON_FILE,
	INVALID_LUIS_JSON_FILE,
	INVALID_QNA_KNOWLEDGE_BASE_JSON_FILE,
	INVALID_QNA_ALTERATIONS_JSON_FILE
}
