"use strict";
/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */
Object.defineProperty(exports, "__esModule", { value: true });
const msRest = require("ms-rest-js");
const Mappers = require("../models/appsMappers");
const Parameters = require("../models/parameters");
/** Class representing a Apps. */
class Apps {
    /**
     * Create a Apps.
     * @param {LuisAuthoringContext} client Reference to the service client.
     */
    constructor(client) {
        this.client = client;
    }
    /**
     * Creates a new LUIS app.
     *
     * @param {ApplicationCreateObject} applicationCreateObject A model containing Name, Description
     * (optional), Culture, Usage Scenario (optional), Domain (optional) and initial version ID
     * (optional) of the application. Default value for the version ID is 0.1. Note: the culture cannot
     * be changed after the app is created.
     *
     * @param {RequestOptionsBase} [options] Optional Parameters.
     *
     * @returns {Promise} A promise is returned
     *
     * @resolve {HttpOperationResponse} The deserialized result object.
     *
     * @reject {Error|ServiceError} The error object.
     */
    addWithHttpOperationResponse(applicationCreateObject, options) {
        return this.client.sendOperationRequest({
            applicationCreateObject,
            options
        }, addOperationSpec);
    }
    /**
     * Lists all of the user applications.
     *
     * @param {AppsListOptionalParams} [options] Optional Parameters.
     *
     * @returns {Promise} A promise is returned
     *
     * @resolve {HttpOperationResponse} The deserialized result object.
     *
     * @reject {Error|ServiceError} The error object.
     */
    listWithHttpOperationResponse(options) {
        return this.client.sendOperationRequest({
            options
        }, listOperationSpec);
    }
    /**
     * Imports an application to LUIS, the application's structure should be included in in the request
     * body.
     *
     * @param {LuisApp} luisApp A LUIS application structure.
     *
     * @param {AppsImportMethodOptionalParams} [options] Optional Parameters.
     *
     * @returns {Promise} A promise is returned
     *
     * @resolve {HttpOperationResponse} The deserialized result object.
     *
     * @reject {Error|ServiceError} The error object.
     */
    importMethodWithHttpOperationResponse(luisApp, options) {
        return this.client.sendOperationRequest({
            luisApp,
            options
        }, importMethodOperationSpec);
    }
    /**
     * Gets the endpoint URLs for the prebuilt Cortana applications.
     *
     * @param {RequestOptionsBase} [options] Optional Parameters.
     *
     * @returns {Promise} A promise is returned
     *
     * @resolve {HttpOperationResponse} The deserialized result object.
     *
     * @reject {Error|ServiceError} The error object.
     */
    listCortanaEndpointsWithHttpOperationResponse(options) {
        return this.client.sendOperationRequest({
            options
        }, listCortanaEndpointsOperationSpec);
    }
    /**
     * Gets the available application domains.
     *
     * @param {RequestOptionsBase} [options] Optional Parameters.
     *
     * @returns {Promise} A promise is returned
     *
     * @resolve {HttpOperationResponse} The deserialized result object.
     *
     * @reject {Error|ServiceError} The error object.
     */
    listDomainsWithHttpOperationResponse(options) {
        return this.client.sendOperationRequest({
            options
        }, listDomainsOperationSpec);
    }
    /**
     * Gets the application available usage scenarios.
     *
     * @param {RequestOptionsBase} [options] Optional Parameters.
     *
     * @returns {Promise} A promise is returned
     *
     * @resolve {HttpOperationResponse} The deserialized result object.
     *
     * @reject {Error|ServiceError} The error object.
     */
    listUsageScenariosWithHttpOperationResponse(options) {
        return this.client.sendOperationRequest({
            options
        }, listUsageScenariosOperationSpec);
    }
    /**
     * Gets the supported application cultures.
     *
     * @param {RequestOptionsBase} [options] Optional Parameters.
     *
     * @returns {Promise} A promise is returned
     *
     * @resolve {HttpOperationResponse} The deserialized result object.
     *
     * @reject {Error|ServiceError} The error object.
     */
    listSupportedCulturesWithHttpOperationResponse(options) {
        return this.client.sendOperationRequest({
            options
        }, listSupportedCulturesOperationSpec);
    }
    /**
     * Gets the query logs of the past month for the application.
     *
     * @param {string} appId The application ID.
     *
     * @param {RequestOptionsBase} [options] Optional Parameters.
     *
     * @returns {Promise} A promise is returned
     *
     * @resolve {HttpOperationResponse} The deserialized result object.
     *
     * @reject {Error|ServiceError} The error object.
     */
    downloadQueryLogsWithHttpOperationResponse(appId, options) {
        return this.client.sendOperationRequest({
            appId,
            options
        }, downloadQueryLogsOperationSpec);
    }
    /**
     * Gets the application info.
     *
     * @param {string} appId The application ID.
     *
     * @param {RequestOptionsBase} [options] Optional Parameters.
     *
     * @returns {Promise} A promise is returned
     *
     * @resolve {HttpOperationResponse} The deserialized result object.
     *
     * @reject {Error|ServiceError} The error object.
     */
    getWithHttpOperationResponse(appId, options) {
        return this.client.sendOperationRequest({
            appId,
            options
        }, getOperationSpec);
    }
    /**
     * Updates the name or description of the application.
     *
     * @param {string} appId The application ID.
     *
     * @param {ApplicationUpdateObject} applicationUpdateObject A model containing Name and Description
     * of the application.
     *
     * @param {RequestOptionsBase} [options] Optional Parameters.
     *
     * @returns {Promise} A promise is returned
     *
     * @resolve {HttpOperationResponse} The deserialized result object.
     *
     * @reject {Error|ServiceError} The error object.
     */
    updateWithHttpOperationResponse(appId, applicationUpdateObject, options) {
        return this.client.sendOperationRequest({
            appId,
            applicationUpdateObject,
            options
        }, updateOperationSpec);
    }
    /**
     * Deletes an application.
     *
     * @param {string} appId The application ID.
     *
     * @param {RequestOptionsBase} [options] Optional Parameters.
     *
     * @returns {Promise} A promise is returned
     *
     * @resolve {HttpOperationResponse} The deserialized result object.
     *
     * @reject {Error|ServiceError} The error object.
     */
    deleteMethodWithHttpOperationResponse(appId, options) {
        return this.client.sendOperationRequest({
            appId,
            options
        }, deleteMethodOperationSpec);
    }
    /**
     * Publishes a specific version of the application.
     *
     * @param {string} appId The application ID.
     *
     * @param {ApplicationPublishObject} applicationPublishObject The application publish object. The
     * region is the target region that the application is published to.
     *
     * @param {RequestOptionsBase} [options] Optional Parameters.
     *
     * @returns {Promise} A promise is returned
     *
     * @resolve {HttpOperationResponse} The deserialized result object.
     *
     * @reject {Error|ServiceError} The error object.
     */
    publishWithHttpOperationResponse(appId, applicationPublishObject, options) {
        return this.client.sendOperationRequest({
            appId,
            applicationPublishObject,
            options
        }, publishOperationSpec);
    }
    /**
     * Get the application settings.
     *
     * @param {string} appId The application ID.
     *
     * @param {RequestOptionsBase} [options] Optional Parameters.
     *
     * @returns {Promise} A promise is returned
     *
     * @resolve {HttpOperationResponse} The deserialized result object.
     *
     * @reject {Error|ServiceError} The error object.
     */
    getSettingsWithHttpOperationResponse(appId, options) {
        return this.client.sendOperationRequest({
            appId,
            options
        }, getSettingsOperationSpec);
    }
    /**
     * Updates the application settings.
     *
     * @param {string} appId The application ID.
     *
     * @param {ApplicationSettingUpdateObject} applicationSettingUpdateObject An object containing the
     * new application settings.
     *
     * @param {RequestOptionsBase} [options] Optional Parameters.
     *
     * @returns {Promise} A promise is returned
     *
     * @resolve {HttpOperationResponse} The deserialized result object.
     *
     * @reject {Error|ServiceError} The error object.
     */
    updateSettingsWithHttpOperationResponse(appId, applicationSettingUpdateObject, options) {
        return this.client.sendOperationRequest({
            appId,
            applicationSettingUpdateObject,
            options
        }, updateSettingsOperationSpec);
    }
    /**
     * Get the application publish settings.
     *
     * @param {string} appId The application ID.
     *
     * @param {RequestOptionsBase} [options] Optional Parameters.
     *
     * @returns {Promise} A promise is returned
     *
     * @resolve {HttpOperationResponse} The deserialized result object.
     *
     * @reject {Error|ServiceError} The error object.
     */
    getPublishSettingsWithHttpOperationResponse(appId, options) {
        return this.client.sendOperationRequest({
            appId,
            options
        }, getPublishSettingsOperationSpec);
    }
    /**
     * Updates the application publish settings.
     *
     * @param {string} appId The application ID.
     *
     * @param {PublishSettingUpdateObject} publishSettingUpdateObject An object containing the new
     * publish application settings.
     *
     * @param {RequestOptionsBase} [options] Optional Parameters.
     *
     * @returns {Promise} A promise is returned
     *
     * @resolve {HttpOperationResponse} The deserialized result object.
     *
     * @reject {Error|ServiceError} The error object.
     */
    updatePublishSettingsWithHttpOperationResponse(appId, publishSettingUpdateObject, options) {
        return this.client.sendOperationRequest({
            appId,
            publishSettingUpdateObject,
            options
        }, updatePublishSettingsOperationSpec);
    }
    /**
     * Returns the available endpoint deployment regions and URLs.
     *
     * @param {string} appId The application ID.
     *
     * @param {RequestOptionsBase} [options] Optional Parameters.
     *
     * @returns {Promise} A promise is returned
     *
     * @resolve {HttpOperationResponse} The deserialized result object.
     *
     * @reject {Error|ServiceError} The error object.
     */
    listEndpointsWithHttpOperationResponse(appId, options) {
        return this.client.sendOperationRequest({
            appId,
            options
        }, listEndpointsOperationSpec);
    }
    /**
     * Gets all the available custom prebuilt domains for all cultures.
     *
     * @param {RequestOptionsBase} [options] Optional Parameters.
     *
     * @returns {Promise} A promise is returned
     *
     * @resolve {HttpOperationResponse} The deserialized result object.
     *
     * @reject {Error|ServiceError} The error object.
     */
    listAvailableCustomPrebuiltDomainsWithHttpOperationResponse(options) {
        return this.client.sendOperationRequest({
            options
        }, listAvailableCustomPrebuiltDomainsOperationSpec);
    }
    /**
     * Adds a prebuilt domain along with its models as a new application.
     *
     * @param {PrebuiltDomainCreateObject} prebuiltDomainCreateObject A prebuilt domain create object
     * containing the name and culture of the domain.
     *
     * @param {RequestOptionsBase} [options] Optional Parameters.
     *
     * @returns {Promise} A promise is returned
     *
     * @resolve {HttpOperationResponse} The deserialized result object.
     *
     * @reject {Error|ServiceError} The error object.
     */
    addCustomPrebuiltDomainWithHttpOperationResponse(prebuiltDomainCreateObject, options) {
        return this.client.sendOperationRequest({
            prebuiltDomainCreateObject,
            options
        }, addCustomPrebuiltDomainOperationSpec);
    }
    /**
     * Gets all the available custom prebuilt domains for a specific culture.
     *
     * @param {string} culture Culture.
     *
     * @param {RequestOptionsBase} [options] Optional Parameters.
     *
     * @returns {Promise} A promise is returned
     *
     * @resolve {HttpOperationResponse} The deserialized result object.
     *
     * @reject {Error|ServiceError} The error object.
     */
    listAvailableCustomPrebuiltDomainsForCultureWithHttpOperationResponse(culture, options) {
        return this.client.sendOperationRequest({
            culture,
            options
        }, listAvailableCustomPrebuiltDomainsForCultureOperationSpec);
    }
    add(applicationCreateObject, options, callback) {
        return msRest.responseToBody(this.addWithHttpOperationResponse.bind(this), applicationCreateObject, options, callback);
    }
    list(options, callback) {
        return msRest.responseToBody(this.listWithHttpOperationResponse.bind(this), options, callback);
    }
    importMethod(luisApp, options, callback) {
        return msRest.responseToBody(this.importMethodWithHttpOperationResponse.bind(this), luisApp, options, callback);
    }
    listCortanaEndpoints(options, callback) {
        return msRest.responseToBody(this.listCortanaEndpointsWithHttpOperationResponse.bind(this), options, callback);
    }
    listDomains(options, callback) {
        return msRest.responseToBody(this.listDomainsWithHttpOperationResponse.bind(this), options, callback);
    }
    listUsageScenarios(options, callback) {
        return msRest.responseToBody(this.listUsageScenariosWithHttpOperationResponse.bind(this), options, callback);
    }
    listSupportedCultures(options, callback) {
        return msRest.responseToBody(this.listSupportedCulturesWithHttpOperationResponse.bind(this), options, callback);
    }
    get(appId, options, callback) {
        return msRest.responseToBody(this.getWithHttpOperationResponse.bind(this), appId, options, callback);
    }
    update(appId, applicationUpdateObject, options, callback) {
        return msRest.responseToBody(this.updateWithHttpOperationResponse.bind(this), appId, applicationUpdateObject, options, callback);
    }
    deleteMethod(appId, options, callback) {
        return msRest.responseToBody(this.deleteMethodWithHttpOperationResponse.bind(this), appId, options, callback);
    }
    publish(appId, applicationPublishObject, options, callback) {
        return msRest.responseToBody(this.publishWithHttpOperationResponse.bind(this), appId, applicationPublishObject, options, callback);
    }
    getSettings(appId, options, callback) {
        return msRest.responseToBody(this.getSettingsWithHttpOperationResponse.bind(this), appId, options, callback);
    }
    updateSettings(appId, applicationSettingUpdateObject, options, callback) {
        return msRest.responseToBody(this.updateSettingsWithHttpOperationResponse.bind(this), appId, applicationSettingUpdateObject, options, callback);
    }
    getPublishSettings(appId, options, callback) {
        return msRest.responseToBody(this.getPublishSettingsWithHttpOperationResponse.bind(this), appId, options, callback);
    }
    updatePublishSettings(appId, publishSettingUpdateObject, options, callback) {
        return msRest.responseToBody(this.updatePublishSettingsWithHttpOperationResponse.bind(this), appId, publishSettingUpdateObject, options, callback);
    }
    listEndpoints(appId, options, callback) {
        return msRest.responseToBody(this.listEndpointsWithHttpOperationResponse.bind(this), appId, options, callback);
    }
    listAvailableCustomPrebuiltDomains(options, callback) {
        return msRest.responseToBody(this.listAvailableCustomPrebuiltDomainsWithHttpOperationResponse.bind(this), options, callback);
    }
    addCustomPrebuiltDomain(prebuiltDomainCreateObject, options, callback) {
        return msRest.responseToBody(this.addCustomPrebuiltDomainWithHttpOperationResponse.bind(this), prebuiltDomainCreateObject, options, callback);
    }
    listAvailableCustomPrebuiltDomainsForCulture(culture, options, callback) {
        return msRest.responseToBody(this.listAvailableCustomPrebuiltDomainsForCultureWithHttpOperationResponse.bind(this), culture, options, callback);
    }
}
exports.Apps = Apps;
// Operation Specifications
const serializer = new msRest.Serializer(Mappers);
const addOperationSpec = {
    httpMethod: "POST",
    path: "luis/api/v2.0/apps/",
    urlParameters: [
        Parameters.endpoint
    ],
    requestBody: {
        parameterPath: "applicationCreateObject",
        mapper: Object.assign({}, Mappers.ApplicationCreateObject, { required: true })
    },
    responses: {
        201: {
            bodyMapper: {
                serializedName: "parsedResponse",
                type: {
                    name: "Uuid"
                }
            }
        },
        default: {
            bodyMapper: Mappers.ErrorResponse
        }
    },
    serializer
};
const listOperationSpec = {
    httpMethod: "GET",
    path: "luis/api/v2.0/apps/",
    urlParameters: [
        Parameters.endpoint
    ],
    queryParameters: [
        Parameters.skip,
        Parameters.take
    ],
    responses: {
        200: {
            bodyMapper: {
                serializedName: "parsedResponse",
                type: {
                    name: "Sequence",
                    element: {
                        type: {
                            name: "Composite",
                            className: "ApplicationInfoResponse"
                        }
                    }
                }
            }
        },
        default: {
            bodyMapper: Mappers.ErrorResponse
        }
    },
    serializer
};
const importMethodOperationSpec = {
    httpMethod: "POST",
    path: "luis/api/v2.0/apps/import",
    urlParameters: [
        Parameters.endpoint
    ],
    queryParameters: [
        Parameters.appName
    ],
    requestBody: {
        parameterPath: "luisApp",
        mapper: Object.assign({}, Mappers.LuisApp, { required: true })
    },
    responses: {
        201: {
            bodyMapper: {
                serializedName: "parsedResponse",
                type: {
                    name: "Uuid"
                }
            }
        },
        default: {
            bodyMapper: Mappers.ErrorResponse
        }
    },
    serializer
};
const listCortanaEndpointsOperationSpec = {
    httpMethod: "GET",
    path: "luis/api/v2.0/apps/assistants",
    urlParameters: [
        Parameters.endpoint
    ],
    responses: {
        200: {
            bodyMapper: Mappers.PersonalAssistantsResponse
        },
        default: {
            bodyMapper: Mappers.ErrorResponse
        }
    },
    serializer
};
const listDomainsOperationSpec = {
    httpMethod: "GET",
    path: "luis/api/v2.0/apps/domains",
    urlParameters: [
        Parameters.endpoint
    ],
    responses: {
        200: {
            bodyMapper: {
                serializedName: "parsedResponse",
                type: {
                    name: "Sequence",
                    element: {
                        type: {
                            name: "String"
                        }
                    }
                }
            }
        },
        default: {
            bodyMapper: Mappers.ErrorResponse
        }
    },
    serializer
};
const listUsageScenariosOperationSpec = {
    httpMethod: "GET",
    path: "luis/api/v2.0/apps/usagescenarios",
    urlParameters: [
        Parameters.endpoint
    ],
    responses: {
        200: {
            bodyMapper: {
                serializedName: "parsedResponse",
                type: {
                    name: "Sequence",
                    element: {
                        type: {
                            name: "String"
                        }
                    }
                }
            }
        },
        default: {
            bodyMapper: Mappers.ErrorResponse
        }
    },
    serializer
};
const listSupportedCulturesOperationSpec = {
    httpMethod: "GET",
    path: "luis/api/v2.0/apps/cultures",
    urlParameters: [
        Parameters.endpoint
    ],
    responses: {
        200: {
            bodyMapper: {
                serializedName: "parsedResponse",
                type: {
                    name: "Sequence",
                    element: {
                        type: {
                            name: "Composite",
                            className: "AvailableCulture"
                        }
                    }
                }
            }
        },
        default: {
            bodyMapper: Mappers.ErrorResponse
        }
    },
    serializer
};
const downloadQueryLogsOperationSpec = {
    httpMethod: "GET",
    path: "luis/api/v2.0/apps/{appId}/querylogs",
    urlParameters: [
        Parameters.endpoint,
        Parameters.appId
    ],
    responses: {
        200: {
            bodyMapper: {
                serializedName: "parsedResponse",
                type: {
                    name: "Stream"
                }
            }
        },
        default: {}
    },
    serializer
};
const getOperationSpec = {
    httpMethod: "GET",
    path: "luis/api/v2.0/apps/{appId}",
    urlParameters: [
        Parameters.endpoint,
        Parameters.appId
    ],
    responses: {
        200: {
            bodyMapper: Mappers.ApplicationInfoResponse
        },
        default: {
            bodyMapper: Mappers.ErrorResponse
        }
    },
    serializer
};
const updateOperationSpec = {
    httpMethod: "PUT",
    path: "luis/api/v2.0/apps/{appId}",
    urlParameters: [
        Parameters.endpoint,
        Parameters.appId
    ],
    requestBody: {
        parameterPath: "applicationUpdateObject",
        mapper: Object.assign({}, Mappers.ApplicationUpdateObject, { required: true })
    },
    responses: {
        200: {
            bodyMapper: Mappers.OperationStatus
        },
        default: {
            bodyMapper: Mappers.ErrorResponse
        }
    },
    serializer
};
const deleteMethodOperationSpec = {
    httpMethod: "DELETE",
    path: "luis/api/v2.0/apps/{appId}",
    urlParameters: [
        Parameters.endpoint,
        Parameters.appId
    ],
    responses: {
        200: {
            bodyMapper: Mappers.OperationStatus
        },
        default: {
            bodyMapper: Mappers.ErrorResponse
        }
    },
    serializer
};
const publishOperationSpec = {
    httpMethod: "POST",
    path: "luis/api/v2.0/apps/{appId}/publish",
    urlParameters: [
        Parameters.endpoint,
        Parameters.appId
    ],
    requestBody: {
        parameterPath: "applicationPublishObject",
        mapper: Object.assign({}, Mappers.ApplicationPublishObject, { required: true })
    },
    responses: {
        201: {
            bodyMapper: Mappers.ProductionOrStagingEndpointInfo
        },
        default: {
            bodyMapper: Mappers.ErrorResponse
        }
    },
    serializer
};
const getSettingsOperationSpec = {
    httpMethod: "GET",
    path: "luis/api/v2.0/apps/{appId}/settings",
    urlParameters: [
        Parameters.endpoint,
        Parameters.appId
    ],
    responses: {
        200: {
            bodyMapper: Mappers.ApplicationSettings
        },
        default: {
            bodyMapper: Mappers.ErrorResponse
        }
    },
    serializer
};
const updateSettingsOperationSpec = {
    httpMethod: "PUT",
    path: "luis/api/v2.0/apps/{appId}/settings",
    urlParameters: [
        Parameters.endpoint,
        Parameters.appId
    ],
    requestBody: {
        parameterPath: "applicationSettingUpdateObject",
        mapper: Object.assign({}, Mappers.ApplicationSettingUpdateObject, { required: true })
    },
    responses: {
        200: {
            bodyMapper: Mappers.OperationStatus
        },
        default: {
            bodyMapper: Mappers.ErrorResponse
        }
    },
    serializer
};
const getPublishSettingsOperationSpec = {
    httpMethod: "GET",
    path: "luis/api/v2.0/apps/{appId}/publishsettings",
    urlParameters: [
        Parameters.endpoint,
        Parameters.appId
    ],
    responses: {
        200: {
            bodyMapper: Mappers.PublishSettings
        },
        default: {
            bodyMapper: Mappers.ErrorResponse
        }
    },
    serializer
};
const updatePublishSettingsOperationSpec = {
    httpMethod: "PUT",
    path: "luis/api/v2.0/apps/{appId}/publishsettings",
    urlParameters: [
        Parameters.endpoint,
        Parameters.appId
    ],
    requestBody: {
        parameterPath: "publishSettingUpdateObject",
        mapper: Object.assign({}, Mappers.PublishSettingUpdateObject, { required: true })
    },
    responses: {
        200: {
            bodyMapper: Mappers.OperationStatus
        },
        default: {
            bodyMapper: Mappers.ErrorResponse
        }
    },
    serializer
};
const listEndpointsOperationSpec = {
    httpMethod: "GET",
    path: "luis/api/v2.0/apps/{appId}/endpoints",
    urlParameters: [
        Parameters.endpoint,
        Parameters.appId
    ],
    responses: {
        200: {
            bodyMapper: {
                serializedName: "parsedResponse",
                type: {
                    name: "Dictionary",
                    value: {
                        type: {
                            name: "String"
                        }
                    }
                }
            }
        },
        default: {
            bodyMapper: Mappers.ErrorResponse
        }
    },
    serializer
};
const listAvailableCustomPrebuiltDomainsOperationSpec = {
    httpMethod: "GET",
    path: "luis/api/v2.0/apps/customprebuiltdomains",
    urlParameters: [
        Parameters.endpoint
    ],
    responses: {
        200: {
            bodyMapper: {
                serializedName: "parsedResponse",
                type: {
                    name: "Sequence",
                    element: {
                        type: {
                            name: "Composite",
                            className: "PrebuiltDomain"
                        }
                    }
                }
            }
        },
        default: {
            bodyMapper: Mappers.ErrorResponse
        }
    },
    serializer
};
const addCustomPrebuiltDomainOperationSpec = {
    httpMethod: "POST",
    path: "luis/api/v2.0/apps/customprebuiltdomains",
    urlParameters: [
        Parameters.endpoint
    ],
    requestBody: {
        parameterPath: "prebuiltDomainCreateObject",
        mapper: Object.assign({}, Mappers.PrebuiltDomainCreateObject, { required: true })
    },
    responses: {
        201: {
            bodyMapper: {
                serializedName: "parsedResponse",
                type: {
                    name: "Uuid"
                }
            }
        },
        default: {
            bodyMapper: Mappers.ErrorResponse
        }
    },
    serializer
};
const listAvailableCustomPrebuiltDomainsForCultureOperationSpec = {
    httpMethod: "GET",
    path: "luis/api/v2.0/apps/customprebuiltdomains/{culture}",
    urlParameters: [
        Parameters.endpoint,
        Parameters.culture
    ],
    responses: {
        200: {
            bodyMapper: {
                serializedName: "parsedResponse",
                type: {
                    name: "Sequence",
                    element: {
                        type: {
                            name: "Composite",
                            className: "PrebuiltDomain"
                        }
                    }
                }
            }
        },
        default: {
            bodyMapper: Mappers.ErrorResponse
        }
    },
    serializer
};
//# sourceMappingURL=apps.js.map